app_dashboard:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/dashboard.html.twig

app_bankaccounts_index:
    path: /bankaccounts
    controller: App\Controller\BankaccountController::overviewAction

app_bankaccounts_update:
    path: /bankaccounts/{id}/update
    controller: App\Controller\BankaccountController::updateAction
