app_dashboard:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/dashboard.html.twig

app_mutation_account_index:
    path: /bankaccounts
    controller: App\Controller\MutationAccountController::indexAction

app_mutation_account_update:
    path: /bankaccounts/{id}/update
    controller: App\Controller\MutationAccountController::updateAction

app_mutation_index:
    path: /mutations
    controller: App\Controller\MutationController::indexAction
