parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventSubscriber\GoogleImageSubscriber:
        arguments: ['%kernel.project_dir%/public/logo']
        tags:
            - { name: doctrine.event_subscriber, connection: default }
