App\Entity\MutationAccount:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        company:
            type: string
            length: 100
        category:
            type: string
            length: 100
