App\Entity\Mutation:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        amount:
            type: integer
            length: 11
        date:
            type: datetime
    manyToOne:
        mutationAccount:
            targetEntity: App\Entity\MutationAccount
            cascade: ["persist"]
            joinColumn:
                name: mutation_account_id
                referencedColumnName: id
